before_script:
  - cd /usr/local/bin

stages:
  - backend
  - frontend

backend-deploy:
  stage: backend
  only:
    - dev
  script:
    - git reset --hard
    - git pull
    - cd backend
    - mvn clean package -B
    - sudo service hyp-backend restart
