before_script:
  - cd /usr/local/bin/hyp-project

stages:
  - backend
  - frontend

backend-deploy:
  stage: backend
  only:
    - dev
  script:
    - git reset --hard
    - git pull
    - cd backend
    - mvn clean package -B
    - sudo service hyp-backend restart

frontend-deploy:
  stage: frontend
  only:
    - dev
  script:
    - cd frontend
    - export HOST=0.0.0.0
    - npm install
    - pm2 kill
    - pm2 start app-config.json
