version: '3.8'
services:
  mysql:
    image: mysql:latest
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=hyp
      - MYSQL_ROOT_PASSWORD=hypermedia project
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  nuxt:
    image: node
  spring:
    image: openjdk:17
volumes:
  db:
    driver: local